src/main/java/com/example/hanaharmonybackend/domain/BaseEntity.java, src/main/java/com/example/hanaharmonybackend/domain/enumerate/GENDER.java, src/main/java/com/example/hanaharmonybackend/payload/ApiResponse.java, src/main/java/com/example/hanaharmonybackend/payload/code/BaseStatus.java, src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java, src/main/java/com/example/hanaharmonybackend/payload/code/ReasonDto.java, src/main/java/com/example/hanaharmonybackend/payload/code/SuccessStatus.java, src/main/java/com/example/hanaharmonybackend/payload/excpetion/CustomException.java, src/main/java/com/example/hanaharmonybackend/payload/excpetion/GlobalExceptionHandler.java, src/main/resources/application.properties, src/main/resources/application.yml
- closes #2 
1. 공통 응답값 설정했고 예외처리는 ErrorStatus에 추가해서해주세요.
2. RDS 연동했습니다.
어떤 변경 사항이 있나요?
=> [FEAT] 공통 응답값 설정, RDS 연동

build.gradle, src/main/java/com/example/hanaharmonybackend/config/JwtAuthFilter.java, src/main/java/com/example/hanaharmonybackend/config/SecurityConfig.java, src/main/java/com/example/hanaharmonybackend/domain/DescImage.java, src/main/java/com/example/hanaharmonybackend/domain/Profile.java, src/main/java/com/example/hanaharmonybackend/repository/DescImageRepository.java, src/main/java/com/example/hanaharmonybackend/repository/ProfileRepository.java, src/main/java/com/example/hanaharmonybackend/service/FileStorageService.java, src/main/java/com/example/hanaharmonybackend/service/ProfileService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ProfileServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/S3FileStorageServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/ProfileController.java, src/main/java/com/example/hanaharmonybackend/web/dto/ProfileCreateRequest.java, src/main/java/com/example/hanaharmonybackend/web/dto/ProfileResponse.java, src/main/resources/application.yml
[feat] 프로필 등록, 조회 api 구현
- closes #7 
- 프로필 등록 api 구현
- 프로필 조회 api 구현
어떤 변경 사항이 있나요?
=> [FEAT] 프로필 등록, 조회 api 구현

.husky/commit-msg, src/main/java/com/example/hanaharmonybackend/domain/Account.java, src/main/java/com/example/hanaharmonybackend/domain/Pocket.java, src/main/java/com/example/hanaharmonybackend/domain/User.java, src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java, src/main/java/com/example/hanaharmonybackend/repository/AccountRepository.java, src/main/java/com/example/hanaharmonybackend/service/AccountCommandService.java, src/main/java/com/example/hanaharmonybackend/service/AccountService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountCommandServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java, src/main/java/com/example/hanaharmonybackend/util/AccountNumberGenerator.java, src/main/java/com/example/hanaharmonybackend/web/controller/AccountController.java, src/main/java/com/example/hanaharmonybackend/web/dto/account/AccountResponse.java
- #5 
회원가입시 계좌정보 자동 생성 구현
계좌 조회 API 구현
어떤 변경 사항이 있나요?
=> [FEAT] 계좌 생성로직, 조회API 구현

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java, src/main/java/com/example/hanaharmonybackend/web/dto/BoardCreateRequest.java
- #9
- 게시글 이미지 s3 변환로직이 빠져있어서 추가했습니다
어떤 변경 사항이 있나요?
=> [FIX] 게시글 이미지 s3 변환 로직 추가

src/main/java/com/example/hanaharmonybackend/domain/User.java, src/main/java/com/example/hanaharmonybackend/service/AuthService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/AuthController.java, src/main/java/com/example/hanaharmonybackend/web/dto/LoginResponse.java
[FEAT] 로그인시 프로필 여부 반환 기능 구현
- #12 
어떤 변경 사항이 있나요?
=> [FEAT] 로그인시 프로필 여부 반환 기능 구현

src/main/java/com/example/hanaharmonybackend/domain/TransactionHistory.java, src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java, src/main/java/com/example/hanaharmonybackend/repository/PocketRepository.java, src/main/java/com/example/hanaharmonybackend/repository/TransactionHistoryRepository.java, src/main/java/com/example/hanaharmonybackend/service/PocketCommandService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketCommandServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/PocketController.java, src/main/java/com/example/hanaharmonybackend/web/dto/pocket/PocketCreateRequest.java, src/main/java/com/example/hanaharmonybackend/web/dto/pocket/PocketCreateResponse.java
- #16 
주머니 생성, 삭제 API
거래내역 테이블 엔티티 생성
어떤 변경 사항이 있나요?
=> [FEAT] 주머니 생성, 삭제 API 구현

src/main/java/com/example/hanaharmonybackend/service/PocketQueryService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketQueryServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/PocketController.java, src/main/java/com/example/hanaharmonybackend/web/dto/pocket/PocketDetailResponse.java, src/main/java/com/example/hanaharmonybackend/web/dto/pocket/PocketTxDto.java
- #25 
주머니 상세 조회 시 입/출금 거래내역을 확인할 수 있습니다.
어떤 변경 사항이 있나요?
=> [FEAT] 주머니 거래내역 조회 구현

src/main/java/com/example/hanaharmonybackend/config/handler/CustomHandshakeHandler.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
- closes #38 
토큰을 쿠키에서 꺼내쓰도록 수정했습니다.
어떤 변경 사항이 있나요?
=> [FIX] 채팅방 API 수정

src/main/java/com/example/hanaharmonybackend/domain/Board.java, src/main/java/com/example/hanaharmonybackend/domain/ChatRoom.java, src/main/java/com/example/hanaharmonybackend/domain/Profile.java, src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java, src/main/java/com/example/hanaharmonybackend/service/ChatMessageService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatMessageServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/ChatController.java, src/main/java/com/example/hanaharmonybackend/web/dto/chatMessage/ChatMessageTransferResponse.java
- closes #27 
채팅방에서 송금하기 API 구현했습니다.
송금이 되면 자동으로 메세지가 전송됩니다.
chatRoom의 isReceived, board의 status 상태가 변경되고 각 사용자들의 매칭횟수가 1 증가합니다.
어떤 변경 사항이 있나요?
=> [FEAT] 채팅방에서 송금 API 구현

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/dto/chatRoom/ChatRoomDetailResponse.java
- closs #38
채팅방 송금여부 응답값 추가했습니다.
어떤 변경 사항이 있나요?
=> [FIX] 채팅방 송금여부 응답값 추가

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/dto/account/AccountResponse.java
- #45 
/home 으로 계좌 조회 시, pocketList에서 pocketId도 반환하도록 추가했습니다.
어떤 변경 사항이 있나요?
=> [FEAT] 계좌 조회 시 pocketId 포함 응답

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/dto/chatRoom/ChatRoomDetailResponse.java
채팅방 단건 조회 시 상대방 이름 추가했습니다.
어떤 변경 사항이 있나요?
=> [FEAT] 채팅방 단건 조회 시 상대방 이름 추가

src/main/java/com/example/hanaharmonybackend/repository/AccountRepository.java, src/main/java/com/example/hanaharmonybackend/repository/BoardRepository.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountCommandServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatMessageServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketCommandServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ProfileServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/AccountController.java, src/main/java/com/example/hanaharmonybackend/web/controller/AuthController.java, src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java, src/main/java/com/example/hanaharmonybackend/web/controller/ProfileController.java
- closes #52 
게시글 정렬, service Transactional 설정, 계좌 조회 코드 수정
어떤 변경 사항이 있나요?
=> [REFACTOR] Service, Controller 코드 리팩토링

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java, src/main/java/com/example/hanaharmonybackend/web/dto/BoardCreateRequest.java
- #53
글 등록시 이미지 등록 선택으로 변경했습니다
어떤 변경 사항이 있나요?
=> [REFACTOR] 글 등록시 이미지 등록 선택으로 변경

src/main/java/com/example/hanaharmonybackend/service/ProfileService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ProfileServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/ProfileController.java
[FEAT] 상대방 프로필 조회
- #36 
- porfile/{userid} 를 통해 해당 userid 프로필 조회
어떤 변경 사항이 있나요?
=> [FEAT] 상대방 프로필 조회

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
- closes #64 
신고하면 상대의 신뢰도가 1 감소됩니다.
어떤 변경 사항이 있나요?
=> [FEAT] 신고 시 신뢰도에 반영

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/dto/account/AccountResponse.java, src/main/java/com/example/hanaharmonybackend/web/dto/account/AccountTxDto.java
- #59 
계좌 상세조회 시, createdAt필드의 날짜, 시간을 분리해서 반환
계좌 조회시 accountId 추가 반환
어떤 변경 사항이 있나요?
=> [FEAT] 계좌 상세조회 반환 값 추가

src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java, src/main/java/com/example/hanaharmonybackend/repository/ChatRoomRepository.java, src/main/java/com/example/hanaharmonybackend/service/BoardService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java, src/main/java/com/example/hanaharmonybackend/web/dto/BoardResponse.java
- closes #68 
- 게시글 상세 조회 시 개설된 채팅방 개수, 개설된 채팅방 리스트 조회 API 구현
- 생성된 채팅방으로 이동하게 chatRoomId 응답값 포함
- 채팅방 간단 정보 공통 메서드로 리팩토링
어떤 변경 사항이 있나요?
=> [FEAT] 게시글 상세 조회시 채팅방 연결

src/main/java/com/example/hanaharmonybackend/domain/Board.java, src/main/java/com/example/hanaharmonybackend/service/BoardService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketCommandServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
- #71 
본인글 수정하는 api 구현했습니다
어떤 변경 사항이 있나요?
=> [FEAT] 본인 글 수정 api 구현

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketQueryServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/dto/pocket/PocketTxDto.java
- #73 
주머니 상세 조회시 반환 값 수정했습니다.
- createdAt -> day, time 으로 분리
- forName, toName 반환값을 계좌번호 -> 소유자 이름으로 변경
어떤 변경 사항이 있나요?
=> [FEAT] 주머니 조회 반환값 수정

src/main/java/com/example/hanaharmonybackend/config/SecurityConfig.java, src/main/java/com/example/hanaharmonybackend/service/AuthService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/AuthController.java, src/main/java/com/example/hanaharmonybackend/web/dto/CheckIdResponse.java, src/main/resources/application.yml
- #77 
- 회원가입 시 아이디 중복 체크 API
- 회원가입 후 초기 자금 4000만원 계좌에 입금
추가했습니다.
어떤 변경 사항이 있나요?
=> [FEAT] 아이디 중복 체크, 초기 자금 입금

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/AuthController.java
- #77 
아이디 중복 체크 시, 중복되는 아이디가 존재할 때
- 기존 DUPLICATE_LOGIN_ID 예외 반환 에서
- true 반환으로 변경
어떤 변경 사항이 있나요?
=> [FIX] 아이디 중복 시 true 반환

src/main/java/com/example/hanaharmonybackend/domain/User.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/dto/SignupRequest.java
=> [FEAT] 회원가입시 위,경도 추가

src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java, src/main/java/com/example/hanaharmonybackend/repository/BoardRepository.java, src/main/java/com/example/hanaharmonybackend/service/BoardService.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java, src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java, src/main/java/com/example/hanaharmonybackend/web/dto/BoardNearbyDto.java
- #84
- 내 주변 6km 반경의 게시글만 조회되도록 api 구현했습니다
- /board/nearby
어떤 변경 사항이 있나요?
=> [FEAT] 거리 기반 게시글 필터링 구현

src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatMessageServiceImpl.java
송금시 금액 포맷을 설정했습니다.
어떤 변경 사항이 있나요?
=> [FEAT] 송금시 금액 포맷 설정

src/main/java/com/example/hanaharmonybackend/domain/Expense.java, src/main/java/com/example/hanaharmonybackend/domain/Income.java, src/main/java/com/example/hanaharmonybackend/repository/ExpenseRepository.java, src/main/java/com/example/hanaharmonybackend/repository/IncomeRepository.java, src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
=> [FEAT] 회원가입시 수입, 지출 내역 생성 트리거

.github/workflows/deploy.yml
- #107 
- GitHub Actions → EC2 자동 배포 워크플로우 추가
- main 브랜치에 push 될 경우, Gradle 빌드 후 EC2에 JAR 배포 및 재실행 수행
어떤 변경 사항이 있나요?
=> [FEAT] EC2 자동 배포 워크플로우 추가

src/main/java/com/example/hanaharmonybackend/util/JwtTokenProvider.java
=> [FIX] principal 인증 방식 수정
